site_name: Mondo Disease Ontology Ingest
theme: material
nav:
  - Getting started: index.md
  - Cite: cite.md
  - History: history.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Mapping progress report: reports/unmapped.md
  - Reference:
    - Developers:
      - Workflows: developer/workflows.md
    - "Mondo sources: Mapping progress report": reports/unmapped.md
    - "Mondo sources: Deprecated terms w/ Mondo xrefs": reports/mapped_deprecated.md
    - Mondo sources:
      - Overview: sources.md
      - DO: sources/doid.md
      - GARD: sources/gard.md
      - ICD10CM: sources/icd10cm.md
      - ICD10WHO: sources/icd10who.md
      - ICD11: sources/icd11.md
      - NCIT: sources/ncit.md
      - OMIM: sources/omim.md
      - ORDO: sources/ordo.md
    - Mondo source metrics:
      - Overview: metrics.md
      - DO: metrics/doid.md
      - GARD: metrics/gard.md
      - ICD10CM: metrics/icd10cm.md
      - ICD10WHO: metrics/icd10who.md
      - ICD11: metrics/icd11.md
      - NCIT: metrics/ncit.md
      - OMIM: metrics/omim.md
      - ORDO: metrics/ordo.md
